git:
  depth: 99999

language: java

addons:
  apt:
    update: true
  chrome: stable

services:
  - xvfb

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome

install: true

jobs:
  include:
    - script: ./gradlew test
