dist: trusty
language: java
jdk: oraclejdk8

addons:
  apt:
    update: true
  chrome: stable

services:
  - xvfb

before_install:
  - chmod +x gradlew
  - export CHROME_BIN=/usr/bin/google-chrome

install: true

before_script:
  - export GRADLE_OPTS=-Dorg.gradle.daemon=false

script:
  - ./gradlew test
