language: java
sudo: required
dist: trusty
jdk:
  - oraclejdk8

install: true

services:
  - xvfb

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    
before_install:
  - chmod +x gradlew   
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
  - ./gradlew test
