dist: trusty

language: java

addons:
  chrome: stable

services:
  - xvfb

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  ⋮

install: true

jobs:
  include:
    - script: ./gradlew test
