language: java

addons:
  apt:
    update: true
  chrome: stable

services:
  - xvfb

before_install:
  - chmod +x gradlew
  - export CHROME_BIN=/usr/bin/google-chrome
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install: true

before_script:
  - export GRADLE_OPTS=-Dorg.gradle.daemon=false

script:
  - ./gradlew test
